on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.22.2'
      - run: |
          if [[ "$(go fmt)" ]]; then
            echo "Go files were not formatted properly"
            exit 1
          fi
          go build
          go test
          go vet
